version: '3'

services:
  frontend:
    build: ./
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - cinemaNetWorks
    volumes:
      - ./:/app

networks:
  cinemaNetWorks:
    driver: bridge